window.OFFICIAL_QUESTION_CARDS = [
  {
    id: "roadcode-core-c1",
    officialId: "C1",
    category: "Official Road Code - Core",
    question: "When visibility is poor, how far away must a person or vehicle be unclear before you must turn on your headlights?",
    answerText: "100 metres.",
    explanation: "Use headlights when you cannot clearly see a person or vehicle 100 metres away.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c2",
    officialId: "C2",
    category: "Official Road Code - Core",
    question: "For how many seconds may a vehicle send out visible smoke before it breaches the Road Code rule?",
    answerText: "More than 10 seconds is not allowed.",
    explanation: "Visible smoke must not continue for more than 10 seconds.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-your-vehicle/important-driver-responsibilities",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c3",
    officialId: "C3",
    category: "Official Road Code - Core",
    question: "Which lights should you use when driving in fog?",
    answerText: "Use dipped headlights. Use fog lamps only in severely reduced visibility.",
    explanation: "Do not use full beam in fog because it reflects back and reduces visibility.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/driving-in-bad-weather",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c4",
    officialId: "C4",
    category: "Official Road Code - Core",
    question: "After passing another vehicle, what is the minimum clear road distance you must have ahead?",
    answerText: "At least 100 metres.",
    explanation: "You must be able to complete the pass safely and have at least 100 metres of clear road ahead.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/key-driving-skills/passing",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c5",
    officialId: "C5",
    category: "Official Road Code - Core",
    question: "If anyone is hurt in a crash, within how many hours must the driver tell a police officer?",
    answerText: "Within 24 hours, and as soon as possible.",
    explanation: "A crash involving injury must be reported to police as soon as possible and within 24 hours.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-things-go-wrong/crashes",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c6",
    officialId: "C6",
    category: "Official Road Code - Core",
    question: "What should you do to avoid being blinded by an oncoming vehicle's headlights?",
    answerText: "Slow down if needed and look towards the left side of your lane or road edge rather than directly at the lights.",
    explanation: "Avoid staring into headlights; use the left road edge as a guide and reduce speed if necessary.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c7",
    officialId: "C7",
    category: "Official Road Code - Core",
    question: "Before crossing a railway level crossing, must you check there is enough space for your vehicle on the other side?",
    answerText: "True.",
    explanation: "Do not enter a level crossing unless there is room for your vehicle to clear it.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-railway-level-crossings",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c8",
    officialId: "C8",
    category: "Official Road Code - Core",
    question: "What should you do when you hear a siren or see red flashing lights from an ambulance or fire engine?",
    answerText: "Safely move left and let it pass. Stop if necessary.",
    explanation: "Make way safely for emergency vehicles without making a sudden dangerous move.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/receiving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c9",
    officialId: "C9",
    category: "Official Road Code - Core",
    question: "At a railway level crossing, what should you do if the train has passed but the red lights are still flashing?",
    answerText: "Keep waiting until the red lights stop flashing.",
    explanation: "Flashing red lights mean you must not cross.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-railway-level-crossings",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c10",
    officialId: "C10",
    category: "Official Road Code - Core",
    question: "For give way rules, how should entrance ways into public car parks be treated?",
    answerText: "As intersections.",
    explanation: "Entrance ways into public car parks are treated as intersections for applying give way rules.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/what-is-an-intersection",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c11",
    officialId: "C11",
    category: "Official Road Code - Core",
    question: "Which following-distance rule should you use in wet or frosty conditions when driving a car?",
    answerText: "The 4-second rule.",
    explanation: "Poor road conditions increase stopping distance, so use a longer following distance.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/driving-in-bad-weather",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c12",
    officialId: "C12",
    category: "Official Road Code - Core",
    question: "Which following-distance rule should you use in normal driving conditions?",
    answerText: "The 2-second rule.",
    explanation: "In normal conditions, keep at least a 2-second following distance.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/key-driving-skills/following-distance",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c13",
    officialId: "C13",
    category: "Official Road Code - Core",
    question: "At a pedestrian crossing without a raised traffic island, who must you stop for?",
    answerText: "Stop for pedestrians on any part of the crossing or waiting to cross.",
    explanation: "Without a raised island, treat the crossing as one crossing and give way to pedestrians.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-other-road-users/sharing-the-road-with-pedestrians",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c14",
    officialId: "C14",
    category: "Official Road Code - Core",
    question: "At a pedestrian crossing with a raised traffic island, who must you stop for?",
    answerText: "Stop for pedestrians on your half of the road or waiting to cross your half.",
    explanation: "A raised island divides the crossing into two separate crossings.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-other-road-users/sharing-the-road-with-pedestrians",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c15",
    officialId: "C15",
    category: "Official Road Code - Core",
    question: "At night on a road with lanes, must you be able to stop in half the length of clear road you can see?",
    answerText: "False.",
    explanation: "On a road with lanes, you must be able to stop in the length of clear road you can see. The half-length rule applies where there are no lanes.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c16",
    officialId: "C16",
    category: "Official Road Code - Core",
    question: "When should you apply the 4-second rule?",
    answerText: "When conditions are poor, such as wet, frosty, icy, dusty or otherwise reduced-visibility conditions.",
    explanation: "Use a longer following distance when stopping may take longer or visibility is reduced.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/key-driving-skills/following-distance",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c17",
    officialId: "C17",
    category: "Official Road Code - Core",
    question: "What should you do when approaching a one-lane bridge?",
    answerText: "Slow down, check the signs and give way if the signs or oncoming traffic require it.",
    explanation: "One-lane bridges use signs to show which direction has priority.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-on-one-lane-bridges",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c18",
    officialId: "C18",
    category: "Official Road Code - Core",
    question: "When are you allowed to pass another vehicle?",
    answerText: "Only when it is safe, legal, and you can complete the pass with enough clear road ahead.",
    explanation: "Do not pass unless the road ahead is clear and you can return safely to your lane.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/key-driving-skills/passing",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c19",
    officialId: "C19",
    category: "Official Road Code - Core",
    question: "Does the legal definition of a road include places such as beaches, bridges, car parks, streets and motorways?",
    answerText: "True.",
    explanation: "The Road Code definition of a road is broad and includes those public-use places.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/what-is-a-road",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c20",
    officialId: "C20",
    category: "Official Road Code - Core",
    question: "Do directions from a police officer override traffic lights, signs and give way rules at an intersection?",
    answerText: "True.",
    explanation: "A police officer's directions take priority.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/receiving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c21",
    officialId: "C21",
    category: "Official Road Code - Core",
    question: "What must you do at traffic signals if you want to turn right but the signal shows a red right arrow?",
    answerText: "Stop and wait until the signal allows the right turn.",
    explanation: "A red arrow means traffic must not move in that direction.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-intersections",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c22",
    officialId: "C22",
    category: "Official Road Code - Core",
    question: "What do flashing yellow traffic signals mean?",
    answerText: "Proceed with care and apply the give way rules.",
    explanation: "Treat the intersection carefully and follow give way rules and signs.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-intersections",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c23",
    officialId: "C23",
    category: "Official Road Code - Core",
    question: "At night, when must you dip your headlights?",
    answerText: "Dip them for oncoming traffic, when following another vehicle, when approaching a police officer directing traffic, and when parked.",
    explanation: "Dipping headlights prevents dazzling other road users.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c24",
    officialId: "C24",
    category: "Official Road Code - Core",
    question: "What is the speed limit when passing a school bus that has stopped for children?",
    answerText: "20 km/h or less.",
    explanation: "This applies until you are well past the bus.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/speed-limits",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c25",
    officialId: "C25",
    category: "Official Road Code - Core",
    question: "At traffic signals showing green, what must you do before turning right?",
    answerText: "Give way to oncoming vehicles going straight or turning left, and to pedestrians crossing your path.",
    explanation: "A green light does not remove normal right-turn give way duties.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-intersections",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c26",
    officialId: "C26",
    category: "Official Road Code - Core",
    question: "After passing an Accident sign, what speed applies until you are past the crash site?",
    answerText: "20 km/h or less.",
    explanation: "Slow down and drive at 20 km/h or less until you have passed the incident site.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/speed-limits",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c27",
    officialId: "C27",
    category: "Official Road Code - Core",
    question: "At a roundabout, must you give way to vehicles that will cross your path from your left?",
    answerText: "False. You usually give way to vehicles from your right.",
    explanation: "Traffic already in or approaching from your right has priority at roundabouts.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-roundabouts",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c28",
    officialId: "C28",
    category: "Official Road Code - Core",
    question: "Which lights must you turn on when driving at night?",
    answerText: "Headlights.",
    explanation: "Use headlights from 30 minutes after sunset until 30 minutes before sunrise.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c29",
    officialId: "C29",
    category: "Official Road Code - Core",
    question: "When may you pass on the left at an intersection if it is safe?",
    answerText: "When the vehicle ahead is signalling or waiting to turn right, or when lanes/road layout allow left-side passing.",
    explanation: "Passing on the left is allowed only in limited safe situations.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/key-driving-skills/passing-at-an-intersection",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c30",
    officialId: "C30",
    category: "Official Road Code - Core",
    question: "What does a speed limit mean?",
    answerText: "The maximum legal speed in good conditions.",
    explanation: "You must drive slower if conditions make the posted limit unsafe.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/speed-limits",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c31",
    officialId: "C31",
    category: "Official Road Code - Core",
    question: "If you are turning left, must you give way to an oncoming vehicle turning right into the same road?",
    answerText: "False.",
    explanation: "A right-turning vehicle generally gives way to an oncoming left-turning vehicle.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-intersections",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c32",
    officialId: "C32",
    category: "Official Road Code - Core",
    question: "How do you signal when going straight through a roundabout?",
    answerText: "Do not signal on approach; signal left after passing the exit before the one you intend to take.",
    explanation: "Signal left before you exit the roundabout.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/signal-use-at-roundabouts",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c33",
    officialId: "C33",
    category: "Official Road Code - Core",
    question: "If you are under 20, what does the zero alcohol limit mean?",
    answerText: "You must not drive after consuming alcohol; even one drink can lead to a charge.",
    explanation: "Drivers under 20 are subject to a zero alcohol limit.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/alcohol-and-drugs-limits",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c34",
    officialId: "C34",
    category: "Official Road Code - Core",
    question: "What must you do when blue and red flashing lights appear behind you?",
    answerText: "Pull over and stop in a safe place.",
    explanation: "Police flashing lights mean you must stop safely and wait for instructions.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/receiving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c35",
    officialId: "C35",
    category: "Official Road Code - Core",
    question: "What must you do when red lights flash at a railway level crossing?",
    answerText: "Stop and wait until the red lights stop flashing.",
    explanation: "Do not cross while red lights are flashing.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/giving-way-at-railway-level-crossings",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c36",
    officialId: "C36",
    category: "Official Road Code - Core",
    question: "When must you signal before turning right?",
    answerText: "Signal for at least 3 seconds before turning.",
    explanation: "Give other road users enough warning before changing direction.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/giving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c37",
    officialId: "C37",
    category: "Official Road Code - Core",
    question: "When must you turn your headlights on?",
    answerText: "From 30 minutes after sunset until 30 minutes before sunrise, and whenever visibility is poor.",
    explanation: "Headlights are required at night and when you cannot clearly see 100 metres ahead.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-conditions-change/night-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c38",
    officialId: "C38",
    category: "Official Road Code - Core",
    question: "When coming out of a driveway, must you give way to anyone on the footpath, cycle path, shared path or road?",
    answerText: "True.",
    explanation: "Driveway traffic must give way to people using the spaces it crosses.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/giving-way/the-give-way-rules",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c39",
    officialId: "C39",
    category: "Official Road Code - Core",
    question: "On an 80 km/h road, when may you speed up after seeing a 100 km/h sign ahead?",
    answerText: "After you pass the 100 km/h sign.",
    explanation: "A higher limit starts at the sign.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/safe-speed-guidelines",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c40",
    officialId: "C40",
    category: "Official Road Code - Core",
    question: "On an 80 km/h road, when must you already be at 60 km/h if a 60 km/h sign is ahead?",
    answerText: "By the time you reach the 60 km/h sign.",
    explanation: "A lower speed limit applies from the sign.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/safe-speed-guidelines",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-core-c41",
    officialId: "C41",
    category: "Official Road Code - Core",
    question: "If you are driving slower than the speed limit and vehicles are following you, what should you do?",
    answerText: "Keep left and pull over as soon as it is safe to let them pass.",
    explanation: "Slow drivers should not hold up traffic when they can safely let others pass.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-limits/slow-drivers",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e1",
    officialId: "E1",
    category: "Official Road Code - Emergency",
    question: "At night on a country road, what is the safest response if your headlights suddenly fail?",
    answerText: "Slow down, move left, get off the road as soon as safely possible, and stop.",
    explanation: "A headlight failure at night is an emergency; your priority is to slow and stop safely clear of traffic.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-things-go-wrong/tips-for-handling-driving-emergencies",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e2",
    officialId: "E2",
    category: "Official Road Code - Emergency",
    question: "If you are a driver involved in a crash, what should you do first?",
    answerText: "Stop and check whether anyone is hurt.",
    explanation: "After a crash, stop immediately and deal with injuries and safety first.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-things-go-wrong/crashes",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e3",
    officialId: "E3",
    category: "Official Road Code - Emergency",
    question: "If you are the driver and hurt somebody in a crash, who must you report it to?",
    answerText: "A police officer.",
    explanation: "A crash involving injury must be reported to police.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-things-go-wrong/crashes",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e4",
    officialId: "E4",
    category: "Official Road Code - Emergency",
    question: "When should you use hazard lights?",
    answerText: "Use them to warn others when your vehicle is a temporary hazard.",
    explanation: "Hazard lights warn other road users that your vehicle is stopped, disabled or creating a hazard.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/giving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e5",
    officialId: "E5",
    category: "Official Road Code - Emergency",
    question: "What should you do if you become sleepy while driving?",
    answerText: "Stop in a safe place and rest or sleep.",
    explanation: "Do not keep driving while fatigued; rest is the safe response.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driver-responsibility/driver-fatigue",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e6",
    officialId: "E6",
    category: "Official Road Code - Emergency",
    question: "When must you pull over and allow an ambulance or fire engine to pass?",
    answerText: "When it is using a siren or flashing red lights.",
    explanation: "Move over safely and let emergency vehicles pass when they are signalling an emergency response.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/receiving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e7",
    officialId: "E7",
    category: "Official Road Code - Emergency",
    question: "What does a reflectorised triangle placed on the side of the road warn you about?",
    answerText: "A crash, breakdown or other hazard ahead.",
    explanation: "Warning triangles are used to alert approaching drivers to a hazard.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/when-things-go-wrong/crashes",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e8",
    officialId: "E8",
    category: "Official Road Code - Emergency",
    question: "A ball bounces onto the road from between parked cars. What should you do?",
    answerText: "Slow down and be prepared to stop.",
    explanation: "A child may follow the ball, so treat it as an urgent hazard.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/hazards/multiple-hazards",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e9",
    officialId: "E9",
    category: "Official Road Code - Emergency",
    question: "What must you do if glass falls from your vehicle onto the road?",
    answerText: "Remove it from the road if you can do so safely.",
    explanation: "Drivers are responsible for hazards that fall from their vehicle.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driver-responsibility/responsible-driving",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-emergency-e10",
    officialId: "E10",
    category: "Official Road Code - Emergency",
    question: "What should you do if an ambulance comes up behind you with flashing red lights or a siren?",
    answerText: "Safely move left and stop if necessary so it can pass.",
    explanation: "Make way for the emergency vehicle without creating another danger.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/signals/receiving-signals",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p1",
    officialId: "P1",
    category: "Official Road Code - Parking",
    question: "What is the closest distance you may park to a vehicle entrance?",
    answerText: "1 metre.",
    explanation: "Do not park closer than 1 metre to a vehicle entrance.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p2",
    officialId: "P2",
    category: "Official Road Code - Parking",
    question: "When may you park in a loading zone?",
    answerText: "Only while loading or unloading goods or passengers, and only for the allowed time.",
    explanation: "Loading zones are not general parking spaces.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/parking-signs",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p3",
    officialId: "P3",
    category: "Official Road Code - Parking",
    question: "When parking downhill on a steep road, what should you do?",
    answerText: "Turn the front wheels towards the kerb, leave the vehicle in reverse gear or park, and apply the parking brake.",
    explanation: "This helps stop the vehicle rolling into traffic if the brake fails.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/how-to-park-safely",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p4",
    officialId: "P4",
    category: "Official Road Code - Parking",
    question: "When may you park over a fire hydrant?",
    answerText: "Only if someone who can move the vehicle stays with it.",
    explanation: "Fire hydrants must remain accessible for emergency use.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p5",
    officialId: "P5",
    category: "Official Road Code - Parking",
    question: "How close may you park to the approach side of a pedestrian crossing if there are no broken yellow lines?",
    answerText: "No closer than 6 metres.",
    explanation: "Parking too close blocks visibility for pedestrians and drivers.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p6",
    officialId: "P6",
    category: "Official Road Code - Parking",
    question: "How close may you park to an intersection if no broken yellow lines are marked?",
    answerText: "No closer than 6 metres.",
    explanation: "Keep intersections clear so drivers can see and turn safely.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p7",
    officialId: "P7",
    category: "Official Road Code - Parking",
    question: "What does a blue parking sign with a wheelchair symbol mean?",
    answerText: "Parking is reserved for vehicles displaying a mobility parking permit.",
    explanation: "Accessible parking spaces are for permit holders.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/parking-signs",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p8",
    officialId: "P8",
    category: "Official Road Code - Parking",
    question: "Can a private motor vehicle stop on a bus stop?",
    answerText: "No.",
    explanation: "Bus stops are reserved for buses.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/parking-signs",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p9",
    officialId: "P9",
    category: "Official Road Code - Parking",
    question: "What does a bus stop sign mean?",
    answerText: "The area is reserved as a bus stop.",
    explanation: "Do not stop or park a private vehicle there.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/parking-signs",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p10",
    officialId: "P10",
    category: "Official Road Code - Parking",
    question: "Can you stop or park over a fire hydrant if someone stays with the vehicle and can move it?",
    answerText: "True.",
    explanation: "Someone must be able to move the vehicle immediately if the hydrant is needed.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p11",
    officialId: "P11",
    category: "Official Road Code - Parking",
    question: "When may you park on the right-hand side of the road?",
    answerText: "Only on a one-way street, unless signs or markings say otherwise.",
    explanation: "On ordinary two-way roads, park on the left-hand side in the direction of travel.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/where-not-to-park",
    verificationStatus: "verified",
  },
  {
    id: "roadcode-parking-p12",
    officialId: "P12",
    category: "Official Road Code - Parking",
    question: "What does a P40 parking sign mean?",
    answerText: "You may park for up to 40 minutes in the direction shown by the arrow, unless extra times or conditions are displayed.",
    explanation: "The number on a P sign shows the maximum parking time in minutes.",
    sourceUrl: "https://www.nzta.govt.nz/roadcode/general-road-code/about-driving/stopping-and-parking/parking-signs",
    verificationStatus: "verified",
  },
];
